deploy:
   provider: pages
   skip_cleanup: true
   on:
     branch: master

language: node_js

node_js:  
  - "7"

before_script:
  - composer config github-oauth.github.com ${GH_TOKEN}


install:
  - composer install --dev --prefer-dist