deploy:
   provider: pages
   skip_cleanup: true
   on:
     branch: master

language: node_js

node_js:  
  - "7"

after_script:
  - git commit -m "Update"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/wuchaofan/wuchaofan.github.com.git" master:master
